# Generated by Django 4.2.5 on 2023-10-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_useradditionalinfo_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradditionalinfo',
            name='avt',
            field=models.ImageField(default='https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_1280.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='useradditionalinfo',
            name='bg',
            field=models.ImageField(default='https://t3.ftcdn.net/jpg/04/53/92/04/360_F_453920448_yMcff4E8ctdXQQegdaQ7WcXnHM3y3aMM.jpg', upload_to=''),
        ),
    ]
