# Generated by Django 4.2.5 on 2023-10-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_useradditionalinfo_avt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradditionalinfo',
            name='avt',
            field=models.ImageField(blank=True, default='https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_1280.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='useradditionalinfo',
            name='bg',
            field=models.ImageField(blank=True, default='https://t3.ftcdn.net/jpg/04/53/92/04/360_F_453920448_yMcff4E8ctdXQQegdaQ7WcXnHM3y3aMM.jpg', null=True, upload_to='images/'),
        ),
    ]
