# Generated by Django 4.2.5 on 2023-10-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_useradditionalinfo_avt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradditionalinfo',
            name='gender',
            field=models.CharField(blank=True, default='None', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='useradditionalinfo',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
