# Generated by Django 4.2.5 on 2023-10-20 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_useradditionalinfo_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradditionalinfo',
            name='created',
        ),
        migrations.RemoveField(
            model_name='useradditionalinfo',
            name='updated',
        ),
    ]
